# Generated by Django 2.2.10 on 2021-05-07 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_auto_20210503_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.IntegerField(choices=[(0, 'worker'), (1, 'teamleader'), (2, 'head of department')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile/images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='teamleader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers_of_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
