# Generated by Django 2.2.10 on 2021-05-08 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charts', '0005_auto_20210507_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='head_of_deportment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_of_deportment', to=settings.AUTH_USER_MODEL),
        ),
    ]
