# Generated by Django 2.2.10 on 2021-05-10 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_auto_20210510_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleader',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charts.Profile'),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
