# Generated by Django 2.2.10 on 2021-05-10 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0009_auto_20210510_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headofdeportment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_of_deportment', to='charts.Profile'),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamleader', to='charts.Profile'),
        ),
    ]
