# Generated by Django 2.2.10 on 2021-05-10 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charts', '0010_auto_20210510_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleader',
            name='HeadOfDeportment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teamleader', to='charts.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_temaleader', to=settings.AUTH_USER_MODEL),
        ),
    ]
