# Generated by Django 2.2.10 on 2021-05-10 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0011_auto_20210510_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleader',
            name='HeadOfDeportment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_of_deportment', to=settings.AUTH_USER_MODEL),
        ),
    ]
