# Generated by Django 2.2.10 on 2021-05-10 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0012_auto_20210510_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='teamleader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamleader', to='charts.TeamLeader'),
        ),
    ]
