# Generated by Django 2.2.10 on 2021-05-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0014_remove_teamleader_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headofdeportment',
            name='profile',
        ),
    ]
