# Generated by Django 2.2.10 on 2021-05-12 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charts', '0016_auto_20210510_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/worker/image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testdata',
            name='teamleader',
        ),
        migrations.AddField(
            model_name='headofdeportment',
            name='image',
            field=models.ImageField(default=1, upload_to='profile/worker/image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamleader',
            name='image',
            field=models.ImageField(default=1, upload_to='profile/worker/image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headofdeportment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_of_deportment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.SmallIntegerField(choices=[(0, 'worker'), (1, 'teamleader'), (2, 'head_of_deportment')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='charts.Worker'),
        ),
        migrations.AddField(
            model_name='worker',
            name='teamleader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamleader', to='charts.TeamLeader'),
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
