# Generated by Django 2.2.10 on 2021-05-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0017_auto_20210512_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headofdeportment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teamleader',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile/worker/image'),
        ),
    ]
